
CREATE TABLE MOTOR(
NOPOL char(8) primary key not null,
WARNA varchar(10) not null,
TIPE varchar(10) not null
)
go
CREATE TABLE PRODUK(
KODEPRODUK char(5) primary key not null,
NAMAPRODUK varchar(20) not null,
HARGA numeric(18,2) not null,
STOK int not null
)

go
CREATE TABLE KARYAWAN(
IDKARYAWAN char(5) primary key not null,
NAMA varchar(50) not null,
ALAMAT varchar(100) not null,
TELP varchar(15),
POSISI varchar(10),
PSWRD varchar(15)
)
go
CREATE TABLE JASA(
KODEJASA char(5) primary key not null,
NAMAJASA char(15) not null,
HARGA numeric(18,2) not null)
go
CREATE TABLE TRANSAKSI(
IDTRANSAKSI CHAR(9) primary key not null,
tanggal datetime
)
go 
CREATE TABLE DETAILTRANSAKSI(
IDTRANSAKSI CHAR(9) REFERENCES TRANSAKSI(IDTRANSAKSI) NOT NULL,
KODEPRODUK CHAR(5) REFERENCES PRODUK(KODEPRODUK) NOT NULL,
KODEJASA CHAR(5) REFERENCES JASA(KODEJASA) NOT NULL,
HARGAPRODUK NUMERIC(18,2) NOT NULL,
JUMLAHPRODUK int NOT NULL
)
go
CREATE TABLE NOTAJASA(
IDTRANSAKSI CHAR(9) REFERENCES TRANSAKSI(IDTRANSAKSI) NOT NULL,
KODEJASA CHAR(5) REFERENCES JASA(KODEJASA) NOT NULL,
HARGA NUMERIC(18,2) NOT NULL
)
--go
CREATE TABLE NOTAPRODUK(
IDTRANSAKSI CHAR(9) REFERENCES TRANSAKSI(IDTRANSAKSI) NOT NULL,
KODEPRODUK CHAR(5) REFERENCES PRODUK(KODEPRODUK) NOT NULL,
HARGAPRODUK NUMERIC(18,2) NOT NULL,
JUMLAHPRODUK int NOT NULL
)
go
CREATE TABLE DETAILMONTIR(
IDTRANSAKSI CHAR(9) REFERENCES TRANSAKSI(IDTRANSAKSI) NOT NULL,
IDKARYAWAN CHAR(5) REFERENCES KARYAWAN(IDKARYAWAN) NOT NULL
)

INSERT INTO MOTOR VALUES('AB3562UU','HITAM','MATIC')
INSERT INTO MOTOR VALUES('BG1530WK','HITAM','MATIC')
GO
INSERT INTO PRODUK VALUES('P0001','Yamalube Matic',26000,12)
INSERT INTO PRODUK VALUES('P0002','AHM Federal 90/90',140000,6)
INSERT INTO PRODUK VALUES('P0003','AHM Oil SPX-1',46500,10)
GO
INSERT INTO KARYAWAN VALUES('K0001','Rere','Yogyakarta','081212121212','Pemilik','123')
INSERT INTO KARYAWAN VALUES('K0002','Pinto','Yogyakarta','081213141516','Kasir','123')
GO
INSERT INTO JASA VALUES('S0001','Ganti Oli bekas','1000')
GO
INSERT INTO TRANSAKSI VALUES('T0001','2018-03-03 10:15:00')

INSERT INTO NOTAPRODUK VALUES('T0001','P0001',26000,1)
SELECT * FROM MOTOR
SELECT * FROM PRODUK
SELECT * FROM KARYAWAN
select * from JASA

--SIA--
CREATE TABLE REKAKUN(
KODEAKUN CHAR(4) PRIMARY KEY,
NAMAAKUN VARCHAR(50) NOT NULL,
JNSSALDO CHAR(1) NOT NULL,
SALDO NUMERIC(18,2)NOT NULL
)

CREATE TABLE JURNAL(
KODEJURNAL CHAR(10) PRIMARY KEY,
TANGGALJURNAL DATETIME NOT NULL,
KETERANGAN VARCHAR(200) NOT NULL,
NOBUKTI CHAR(10) NOT NULL
)

CREATE TABLE DETAILJURNAL(
KODEJURNAL CHAR(10) FOREIGN KEY REFERENCES JURNAL(KODEJURNAL),
REF CHAR(4) FOREIGN KEY REFERENCES REKAKUN(KODEAKUN),
NOMINAL NUMERIC(18,2) NOT NULL,
JNSNOM CHAR(1) NOT NULL
)

CREATE TABLE HISTORY(
KODEHISTORY CHAR(4) PRIMARY KEY,
PERIODE DATETIME NOT NULL
)

CREATE TABLE HISTORYSALDO(
KODEHISTORY CHAR(4) FOREIGN KEY REFERENCES HISTORY(KODEHISTORY),
KODEAKUN CHAR (4) FOREIGN KEY REFERENCES REKAKUN (KODEAKUN),
SALDO NUMERIC (18,2) NOT NULL
)

--FC KODEAKUN
CREATE FUNCTION FC_KODEAKUN(@KEL CHAR(2))
RETURNS CHAR(4) AS
BEGIN
DECLARE @KODEBARU CHAR(4), @AKHIR INT
SELECT @AKHIR=MAX(RIGHT(KODEAKUN,2)) FROM REKAKUN
WHERE LEFT(KODEAKUN,2)=@KEL
IF @AKHIR IS NULL
SET @AKHIR = 0
SET @KODEBARU=@KEL+RIGHT('O' + CAST(@AKHIR + 1 AS VARCHAR(2)),2)
RETURN @KODEBARU
END

--FC NOJURNAL
CREATE FUNCTION FC_KODEJURNAL(@TGL DATETIME)
RETURNS CHAR(10)AS
BEGIN
DECLARE @KODEBARU CHAR(10),
@AKHIR INT, @CTGL CHAR(4)
SET @CTGL = CONVERT(CHAR(4),@TGL,12)
SELECT @AKHIR = MAX (RIGHT(KODEJURNAL,4)) FROM JURNAL
WHERE SUBSTRING (KODEJURNAL,3,4)=@CTGL
IF @AKHIR IS NULL
SET @AKHIR =0
SET @KODEBARU ='J-'+@CTGL+RIGHT('000'+CAST(@AKHIR+1 AS VARCHAR (4)),4)
RETURN @KODEBARU
END

--PROC INSERTAKUN
CREATE PROC SP_INSERTAKUN (@KEL CHAR(2), @NAMA VARCHAR(30))
AS
BEGIN TRAN
DECLARE @KODE CHAR(4), @JNS CHAR
SET @KODE=DBO.FC_KODEAKUN(@KEL)
IF LEFT(@KODE,1) IN (1,5,6)
SET @JNS='D'
ELSE
SET @JNS='K'
INSERT INTO REKAKUN VALUES(@KODE,@NAMA,@JNS,0)
IF @@ERROR=0
COMMIT TRAN
ELSE
ROLLBACK TRAN

--PROC INSERTJURNAL
CREATE PROC SP_INSERTJURNAL (@TJ DATETIME, @KET VARCHAR(200), @NB CHAR(10))
AS
BEGIN TRAN
DECLARE @KJ CHAR(10)
SET @KJ = DBO.FC_KODEJURNAL (@TJ)
INSERT INTO JURNAL VALUES (@KJ, @TJ, @KET, @NB)
IF @@ERROR =0
COMMIT TRAN
ELSE
ROLLBACK TRAN
